language: python
python:
 - "2.7"
install:
 - pip install -r requirements.txt
notifications:
 irc: chat.freenode.net#bpilgrim
 email:
  recipients:
   - KlingmannM@gmail.com
   - williamkmanire@gmail.com
  on_success: always
  on_failed: always
scripts:
 - nosetests tests