language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
notifications:
  irc: chat.freenode.net#pygame2
  email:
  recipients:
    - KlingmannM@gmail.com
    - williamkmanire@gmail.com
  on_success: always
  on_failed: always
script:
  - nosetests tests
  - python integrationtests/remotelawnmowerultra.py
after_success:
 - coveralls
